# Generated by Django 3.0.7 on 2020-07-01 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('branche_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name_branche', models.CharField(max_length=100)),
                ('conservative', models.CharField(choices=[('صنعاء', 'صنعاء'), ('صعده ', 'صعده '), ('المحويت', 'المحويت'), ('عمران', 'عمران '), ('ذمار', 'ذمار '), ('مارب', 'مارب'), ('عدن', 'عدن')], max_length=30)),
                ('directorated', models.CharField(max_length=30)),
                ('date_created', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sign_up',
            fields=[
                ('user_name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=100)),
                ('st_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('job', models.CharField(default='user', max_length=50)),
                ('phon', models.IntegerField()),
                ('date_job', models.DateField(auto_now=True)),
                ('conservative_user', models.CharField(choices=[('صنعاء', 'صنعاء'), ('صعده ', 'صعده '), ('المحويت', 'المحويت'), ('عمران', 'عمران '), ('ذمار', 'ذمار '), ('مارب', 'مارب'), ('عدن', 'عدن')], max_length=30)),
                ('directorated_user', models.CharField(max_length=30)),
                ('branche_id_for', models.CharField(default='الرئيسي', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id_transfer', models.AutoField(primary_key=True, serialize=False)),
                ('name_send', models.CharField(help_text='plase enter name sender', max_length=200)),
                ('phon_send', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('courrency', models.CharField(max_length=30)),
                ('date_send', models.DateTimeField(auto_now=True)),
                ('name_recipient', models.CharField(max_length=200)),
                ('phon_recipient', models.IntegerField()),
                ('situation', models.BooleanField(default=True)),
                ('recipient_card_type', models.CharField(max_length=50)),
                ('id_user_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='cashier.Sign_up')),
            ],
        ),
        migrations.CreateModel(
            name='Transfers_dsactvita',
            fields=[
                ('id_transfer_d', models.IntegerField(primary_key=True, serialize=False)),
                ('name_send_d', models.CharField(help_text='plase enter name sender', max_length=200)),
                ('phon_send_d', models.IntegerField()),
                ('amount_d', models.IntegerField()),
                ('courrency_d', models.CharField(max_length=30)),
                ('date_send_d', models.DateTimeField(auto_now=True)),
                ('name_recipient_d', models.CharField(max_length=200)),
                ('phon_recipient_d', models.IntegerField()),
                ('situation_d', models.BooleanField(default=True)),
                ('recipient_card_num_d', models.IntegerField()),
                ('recipient_card_type_d', models.CharField(max_length=50)),
                ('date_receipt_d', models.DateField()),
                ('id_user_receipt_d', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='cashier.Sign_up')),
                ('id_user_sender_d', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_d', to='cashier.Transfers')),
            ],
        ),
    ]
