# Generated by Django 3.0.7 on 2020-07-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign_up',
            name='branche_id_for',
            field=models.CharField(choices=[(1, 'الفرع الرئيسي'), (2, 'فرع عمران'), (3, 'فرع صعده')], default='الرئيسي', max_length=30),
        ),
    ]
