# Generated by Django 3.0.7 on 2020-07-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0002_auto_20200701_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign_up',
            name='branche_id_for',
            field=models.CharField(choices=[('صنعاء', 'صنعاء'), ('صعده ', 'صعده '), ('المحويت', 'المحويت'), ('عمران', 'عمران '), ('ذمار', 'ذمار '), ('مارب', 'مارب'), ('عدن', 'عدن')], default='الرئيسي', max_length=30),
        ),
    ]
