# Generated by Django 3.0.7 on 2020-07-01 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0003_auto_20200702_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign_up',
            name='branche_id_for',
            field=models.CharField(choices=[(1, 'الفرع الرئيسي'), (2, 'فرع صعده'), (3, 'فرع عمران')], default='الرئيسي', max_length=30),
        ),
        migrations.AlterField(
            model_name='transfers_dsactvita',
            name='id_user_receipt_d',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='cashier.Sign_up'),
        ),
        migrations.AlterField(
            model_name='transfers_dsactvita',
            name='id_user_sender_d',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_d', to='cashier.Transfers'),
        ),
    ]
