# Generated by Django 3.0.7 on 2020-07-02 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashier', '0006_auto_20200702_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfers',
            name='id_user_sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transfers_dsactvita',
            name='id_user_receipt_d',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transfers_dsactvita',
            name='id_user_sender_d',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_d', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Sign_up',
        ),
    ]
