# Generated by Django 3.0.7 on 2020-07-03 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0007_auto_20200702_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfers_dsactvita',
            name='situation_d',
            field=models.BooleanField(default=False),
        ),
    ]
