# Generated by Django 3.0.7 on 2020-07-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0008_auto_20200703_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfers_dsactvita',
            name='date_receipt_d',
            field=models.DateField(auto_now=True),
        ),
    ]
