# Generated by Django 3.0.7 on 2020-07-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0009_auto_20200703_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfers',
            name='courrency',
            field=models.CharField(choices=[(1, 'الفرع الرئيسي'), (2, 'فرع صعده'), (3, 'فرع عمران'), (4, 'فرع صعده'), (5, 'osma'), (6, 'qusiy')], max_length=30),
        ),
        migrations.AlterField(
            model_name='transfers',
            name='id_transfer',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
